# Cereal analysis 
import pandas as pd

# if you want data you can use kaggle.com sign up there

# search cereal in datasets

# choose 80 cearls

In [2]:
import pandas as pd



# Please refer to this sheet 
- https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

or this general one in which you can search 
- https://pandas.pydata.org/docs/search.html?q=droppna

an example dropna search:
- https://pandas.pydata.org/docs/search.html?q=dropna


In [37]:
dir(pd)
df= pd.read_csv('./cereal.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      77 non-null     object 
 1   mfr       77 non-null     object 
 2   type      77 non-null     object 
 3   calories  77 non-null     int64  
 4   protein   77 non-null     int64  
 5   fat       77 non-null     int64  
 6   sodium    77 non-null     int64  
 7   fiber     77 non-null     float64
 8   carbo     77 non-null     float64
 9   sugars    77 non-null     int64  
 10  potass    77 non-null     int64  
 11  vitamins  77 non-null     int64  
 12  shelf     77 non-null     int64  
 13  weight    77 non-null     float64
 14  cups      77 non-null     float64
 15  rating    77 non-null     float64
dtypes: float64(5), int64(8), object(3)
memory usage: 9.8+ KB


In [38]:
df.head()
df.tail(6)

name mfr type  calories  protein  fat  sodium  fiber  \
71    Total Whole Grain   G    C       100        3    1     200    3.0   
72              Triples   G    C       110        2    1     250    0.0   
73                 Trix   G    C       110        1    1     140    0.0   
74           Wheat Chex   R    C       100        3    1     230    3.0   
75             Wheaties   G    C       100        3    1     200    3.0   
76  Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
71   16.0       3     110       100      3     1.0  1.00  46.658844  
72   21.0       3      60        25      3     1.0  0.75  39.106174  
73   13.0      12      25        25      2     1.0  1.00  27.753301  
74   17.0       3     115        25      1     1.0  0.67  49.787445  
75   17.0       3     110        25      1     1.0  1.00  51.592193  
76   16.0       8      60        25      1     1.0  0.75  36.187559

In [5]:
df['name']

0                     100% Bran
1             100% Natural Bran
2                      All-Bran
3     All-Bran with Extra Fiber
4                Almond Delight
                ...            
72                      Triples
73                         Trix
74                   Wheat Chex
75                     Wheaties
76          Wheaties Honey Gold
Name: name, Length: 77, dtype: object

In [6]:
#filter df by col
df[['name','mfr']]

name mfr
0                   100% Bran   N
1           100% Natural Bran   Q
2                    All-Bran   K
3   All-Bran with Extra Fiber   K
4              Almond Delight   R
..                        ...  ..
72                    Triples   G
73                       Trix   G
74                 Wheat Chex   R
75                   Wheaties   G
76        Wheaties Honey Gold   G

[77 rows x 2 columns]

In [7]:
df.set_index("name")

mfr type  calories  protein  fat  sodium  fiber  \
name                                                                        
100% Bran                   N    C        70        4    1     130   10.0   
100% Natural Bran           Q    C       120        3    5      15    2.0   
All-Bran                    K    C        70        4    1     260    9.0   
All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
Almond Delight              R    C       110        2    2     200    1.0   
...                        ..  ...       ...      ...  ...     ...    ...   
Triples                     G    C       110        2    1     250    0.0   
Trix                        G    C       110        1    1     140    0.0   
Wheat Chex                  R    C       100        3    1     230    3.0   
Wheaties                    G    C       100        3    1     200    3.0   
Wheaties Honey Gold         G    C       110        2    1     200    1.0   

                           carbo  sugars  potass  vitamins  shelf  weight  \
name                                                                        
100% Bran                    5.0       6     280        25      3     1.0   
100% Natural Bran            8.0       8     135         0      3     1.0   
All-Bran                     7.0       5     320        25      3     1.0   
All-Bran with Extra Fiber    8.0       0     330        25      3     1.0   
Almond Delight              14.0       8      -1        25      3     1.0   
...                          ...     ...     ...       ...    ...     ...   
Triples                     21.0       3      60        25      3     1.0   
Trix                        13.0      12      25        25      2     1.0   
Wheat Chex                  17.0       3     115        25      1     1.0   
Wheaties                    17.0       3     110        25      1     1.0   
Wheaties Honey Gold         16.0       8      60        25      1     1.0   

                           cups     rating  
name                                        
100% Bran                  0.33  68.402973  
100% Natural Bran          1.00  33.983679  
All-Bran                   0.33  59.425505  
All-Bran with Extra Fiber  0.50  93.704912  
Almond Delight             0.75  34.384843  
...                         ...        ...  
Triples                    0.75  39.106174  
Trix                       1.00  27.753301  
Wheat Chex                 0.67  49.787445  
Wheaties                   1.00  51.592193  
Wheaties Honey Gold        0.75  36.187559  

[77 rows x 15 columns]

In [8]:
df[["name","mfr"]].head(5)

name mfr
0                  100% Bran   N
1          100% Natural Bran   Q
2                   All-Bran   K
3  All-Bran with Extra Fiber   K
4             Almond Delight   R

In [9]:
new_df=df[["name","rating","sugars"]].sort_values('rating', ascending=False)
new_df

name     rating  sugars
3   All-Bran with Extra Fiber  93.704912       0
64     Shredded Wheat 'n'Bran  74.472949       0
65  Shredded Wheat spoon size  72.801787       0
0                   100% Bran  68.402973       6
63             Shredded Wheat  68.235885       0
..                        ...        ...     ...
14                Cocoa Puffs  22.736446      13
18              Count Chocula  22.396513      13
35           Honey Graham Ohs  21.871292      11
12      Cinnamon Toast Crunch  19.823573       9
10               Cap'n'Crunch  18.042851      12

[77 rows x 3 columns]

# Find the average sodium
 

In [10]:
avg_sod=df[["sodium"]].mean()
avg_sod

sodium    159.675325
dtype: float64

# Find the food with the highest carbo 


In [11]:
carbo=df[["carbo"]].max()
carbo

carbo    23.0
dtype: float64

In [12]:
food_rating=df[df['rating']>50] [['name','sugars']]
food_rating
food_rating.set_index('name')


sugars
name                             
100% Bran                       6
All-Bran                        5
All-Bran with Extra Fiber       0
Bran Flakes                     5
Cheerios                        1
Cream of Wheat (Quick)          0
Frosted Mini-Wheats             7
Grape Nuts Flakes               5
Grape-Nuts                      3
Maypo                           3
Nutri-grain Wheat               2
Puffed Rice                     0
Puffed Wheat                    0
Quaker Oatmeal                 -1
Raisin Squares                  6
Shredded Wheat                  0
Shredded Wheat 'n'Bran          0
Shredded Wheat spoon size       0
Special K                       3
Strawberry Fruit Wheats         5
Wheaties                        3

In [39]:
mcc=df["carbo"].mode()
mcc
# mcc2=df["carbo"].mean()
# mcc2

0    13.0
1    15.0
dtype: float64

In [41]:
import numpy as np
df[df['carbo']== np.mean(mcc)]
# the mode is between 13 and 15 so the mean is the avg which is 14 

name mfr type  calories  protein  fat  sodium  fiber  \
4        Almond Delight   R    C       110        2    2     200    1.0   
25       Frosted Flakes   K    C       110        1    0     200    1.0   
26  Frosted Mini-Wheats   K    C       100        3    0       0    3.0   
28        Fruitful Bran   K    C       120        3    0     240    5.0   
37           Honey-comb   P    C       110        1    0     180    0.0   
56   Quaker Oat Squares   Q    C       100        4    1     135    2.0   
58          Raisin Bran   K    C       120        3    1     210    5.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
4    14.0       8      -1        25      3    1.00  0.75  34.384843  
25   14.0      11      25        25      1    1.00  0.75  31.435973  
26   14.0       7     100        25      2    1.00  0.80  58.345141  
28   14.0      12     190        25      3    1.33  0.67  41.015492  
37   14.0      11      35        25      1    1.00  1.33  28.742414  
56   14.0       6     110        25      3    1.00  0.50  49.511874  
58   14.0      12     240        25      2    1.33  0.75  39.259197

In [15]:
df[df['carbo']== np.mean(mcc)][['name','carbo']]

name  carbo
4        Almond Delight   14.0
25       Frosted Flakes   14.0
26  Frosted Mini-Wheats   14.0
28        Fruitful Bran   14.0
37           Honey-comb   14.0
56   Quaker Oat Squares   14.0
58          Raisin Bran   14.0

In [16]:
df[df['carbo']== np.mean(mcc)][['name','carbo']].set_index('name')

carbo
name                      
Almond Delight        14.0
Frosted Flakes        14.0
Frosted Mini-Wheats   14.0
Fruitful Bran         14.0
Honey-comb            14.0
Quaker Oat Squares    14.0
Raisin Bran           14.0

In [17]:
# standard Deviation 
df['potass'].std()


71.28681250926212

In [20]:
#aggregate functions 
##same manufacture grouping and check other criteria 
# what is the median value for protein and sugars for/per each manfuacturer? 
df[['mfr','sugars','protein']].groupby('mfr').median()

sugars  protein
mfr                 
A       3.0      4.0
G       8.5      2.0
K       7.0      3.0
N       0.0      3.0
P      10.0      3.0
Q       6.0      2.5
R       5.5      2.0

In [23]:
def man_name(mfr):
    map={
        "A": 'halal',
        "G": "General mills",
        "K":"Kellogs",
        "N":"Nabisco",
        "Q": "quaker",
        "P":"Post",
        "R":"Ralph"
    }
    return map.get(mfr)

man_name('R')


'Ralph'

In [24]:
# col is series in pandas
df['mfr'].apply(man_name)

0           Nabisco
1            quaker
2           Kellogs
3           Kellogs
4             Ralph
          ...      
72    General mills
73    General mills
74            Ralph
75    General mills
76    General mills
Name: mfr, Length: 77, dtype: object

In [26]:
df['Manufacturer']= df['mfr'].apply(man_name)
df

name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
1           100% Natural Bran   Q    C       120        3    5      15    2.0   
2                    All-Bran   K    C        70        4    1     260    9.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4              Almond Delight   R    C       110        2    2     200    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2    1     250    0.0   
73                       Trix   G    C       110        1    1     140    0.0   
74                 Wheat Chex   R    C       100        3    1     230    3.0   
75                   Wheaties   G    C       100        3    1     200    3.0   
76        Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  \
0     5.0       6     280        25      3     1.0  0.33  68.402973   
1     8.0       8     135         0      3     1.0  1.00  33.983679   
2     7.0       5     320        25      3     1.0  0.33  59.425505   
3     8.0       0     330        25      3     1.0  0.50  93.704912   
4    14.0       8      -1        25      3     1.0  0.75  34.384843   
..    ...     ...     ...       ...    ...     ...   ...        ...   
72   21.0       3      60        25      3     1.0  0.75  39.106174   
73   13.0      12      25        25      2     1.0  1.00  27.753301   
74   17.0       3     115        25      1     1.0  0.67  49.787445   
75   17.0       3     110        25      1     1.0  1.00  51.592193   
76   16.0       8      60        25      1     1.0  0.75  36.187559   

     Manufacturer  
0         Nabisco  
1          quaker  
2         Kellogs  
3         Kellogs  
4           Ralph  
..            ...  
72  General mills  
73  General mills  
74          Ralph  
75  General mills  
76  General mills  

[77 rows x 17 columns]

In [28]:
items=["a","b","c"]
for index,item in enumerate(items):
    print(index)
    print(item)

0
a
1
b
2
c


# Things to figure out for the lab
- Slicing 
- iloc
- handling bad/missing data using droppna/fillna
- date_time.now
- isnull
- indexing
- dig into data to find patterns or make sense a data set
- 

In [32]:
# nums=[1,2,3]
# nums+4
# Broadcasting technique: applying value across all values of list
a= np.array([1,2,3])
print(a)
b=4
print(b)
c=a+b
print(c)

[1 2 3]
4
[5 6 7]


In [35]:
# same but in 2 dim array (usually in images)
a= np.array([[1,2,3],[5,6,7]])
print(a)
b=4
print(b)
c=a+b
print(c)

[[1 2 3]
 [5 6 7]]
4
[[ 5  6  7]
 [ 9 10 11]]


In [36]:
a= np.array([[1,2,3],[5,6,7]])
print(a)
b=np.array([3,2,1])
print(b)
c=a+b
print(c)

[[1 2 3]
 [5 6 7]]
[3 2 1]
[[4 4 4]
 [8 8 8]]
